=== 9mm-exchange/9mm-frontend-v4/packages/token-lists/schema/pancakeswap.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "pancakeswap",
  "title": "9mm Swap Token List",
  "description": "Schema for lists of tokens compatible with the 9mm Swap Interface, including Uniswap standard and 9mm Swap Aptos",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when tokens are removed from the list or token addresses are changed.",
          "minimum": 0,
          "examples": [1, 2]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when tokens are added to the list.",
          "minimum": 0,
          "examples": [0, 1]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [0, 1]
        }
      },
      "required": ["major", "minor", "patch"]
    },
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 10,
      "pattern": "^[\\w]+$",
      "examples": ["compound", "stablecoin"]
    },
    "ExtensionIdentifier": {
      "type": "string",
      "description": "The name of a token extension property",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[\\w]+$",
      "examples": ["color", "is_fee_on_transfer", "aliases"]
    },
    "ExtensionMap": {
      "type": "object",
      "description": "An object containing any arbitrary or vendor-specific token metadata",
      "maxProperties": 10,
      "propertyNames": {
        "$ref": "#/definitions/ExtensionIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/ExtensionValue"
      },
      "examples": [
        {
          "color": "#000000",
          "is_verified_by_me": true
        },
        {
          "x-bridged-addresses-by-chain": {
            "1": {
              "bridgeAddress": "0x4200000000000000000000000000000000000010",
              "tokenAddress": "0x4200000000000000000000000000000000000010"
            }
          }
        }
      ]
    },
    "ExtensionPrimitiveValue": {
      "anyOf": [
        {
          "type": "string",
          "minLength": 1,
          "maxLength": 42,
          "examples": ["#00000"]
        },
        {
          "type": "boolean",
          "examples": [true]
        },
        {
          "type": "number",
          "examples": [15]
        },
        {
          "type": "null"
        }
      ]
    },
    "ExtensionValue": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner0"
          }
        }
      ]
    },
    "ExtensionValueInner0": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner1"
          }
        }
      ]
    },
    "ExtensionValueInner1": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        }
      ]
    },
    "TagDefinition": {
      "type": "object",
      "description": "Definition of a tag that can be associated with a token via its identifier",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the tag",
          "pattern": "^[ \\w]+$",
          "minLength": 1,
          "maxLength": 20
        },
        "description": {
          "type": "string",
          "description": "A user-friendly description of the tag",
          "pattern": "^[ \\w\\.,:]+$",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": ["name", "description"],
      "examples": [
        {
          "name": "Stablecoin",
          "description": "A token with value pegged to another asset"
        }
      ]
    },
    "TokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Ethereum network where this token is deployed",
          "minimum": 1,
          "examples": [1, 42]
        },
        "address": {
          "type": "string",
          "description": "The checksummed address of the token on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": ["0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [18]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40,
          "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
          "examples": ["USD Coin"]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token; must be alphanumeric",
          "pattern": "^[a-zA-Z0-9+\\-%/$.\\s]+$",
          "minLength": 1,
          "maxLength": 20,
          "examples": ["USDC"]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": ["stablecoin", "compound"]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": ["chainId", "address", "decimals", "name", "symbol"]
    },
    "AptosTokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Aptos network where this token is deployed, 0 is devent",
          "minimum": 0,
          "examples": [1, 42]
        },
        "address": {
          "type": "string",
          "description": "The address of the coin on the specified chain ID",
          "examples": ["0x1::aptos_coin::AptosCoin"]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [18]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40,
          "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
          "examples": ["USD Coin"]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token; must be alphanumeric",
          "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
          "minLength": 1,
          "maxLength": 20,
          "examples": ["USDC"]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": ["stablecoin", "compound"]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": ["chainId", "address", "decimals", "name", "symbol"]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the token list",
      "minLength": 1,
      "maxLength": 30,
      "pattern": "^[\\w ]+$",
      "examples": ["My Token List"]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "schema": {
      "type": "string"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "tokens": {
      "type": "array",
      "description": "The list of tokens included in the list",
      "minItems": 1,
      "maxItems": 10000
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the list; may be used in list discoverability",
      "items": {
        "type": "string",
        "description": "A keyword to describe the contents of the list",
        "minLength": 1,
        "maxLength": 20,
        "pattern": "^[\\w ]+$",
        "examples": ["compound", "lending", "personal tokens"]
      },
      "maxItems": 20,
      "uniqueItems": true
    },
    "tags": {
      "type": "object",
      "description": "A mapping of tag identifiers to their name and description",
      "propertyNames": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/TagDefinition"
      },
      "maxProperties": 20,
      "examples": [
        {
          "stablecoin": {
            "name": "Stablecoin",
            "description": "A token with value pegged to another asset"
          }
        }
      ]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the token list; prefer SVG or PNG of size 256x256",
      "format": "uri",
      "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
    }
  },
  "if": {
    "properties": { "schema": { "const": "aptos" } },
    "required": ["name", "timestamp", "version", "tokens", "schema"]
  },
  "then": {
    "properties": {
      "tokens": {
        "items": {
          "$ref": "#/definitions/AptosTokenInfo"
        },
        "type": "array",
        "description": "The list of tokens included in the list",
        "minItems": 1,
        "maxItems": 10000
      }
    }
  },
  "else": {
    "properties": {
      "tokens": {
        "items": {
          "$ref": "#/definitions/TokenInfo"
        },
        "type": "array",
        "description": "The list of tokens included in the list",
        "minItems": 1,
        "maxItems": 10000
      }
    }
  },
  "required": ["name", "timestamp", "version", "tokens"]
}

=== 9mm-exchange/9mm-frontend-v4/apps/web/src/config/constants/tokenLists/pancake-supported-onramp-currency-list.json
{
  "name": "9mm Swap OnRamp List",
  "timestamp": "2022-01-26T11:45:09Z",
  "version": {
    "major": 4,
    "minor": 0,
    "patch": 0
  },
  "tags": {},
  "logoURI": "https://pancakeswap.finance/logo.png",
  "keywords": ["pancake", "default"],
  "tokens": [
    {
      "name": "Binance Pegged USDT",
      "symbol": "USDT",
      "address": "0x55d398326f99059fF775485246999027B3197955",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/0x55d398326f99059fF775485246999027B3197955.png"
    },
    {
      "name": "Binance Pegged USD Coin",
      "symbol": "USDC",
      "address": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d.png"
    },
    {
      "name": "USD Coin",
      "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "symbol": "USDC",
      "decimals": 6,
      "chainId": 1,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "Tether USD",
      "address": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
      "symbol": "USDT",
      "decimals": 6,
      "chainId": 1,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdt.png"
    },
    {
      "name": "DAI StableCoin",
      "address": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "symbol": "DAI",
      "decimals": 18,
      "chainId": 1,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/dai.png"
    },
    {
      "name": "Wrapped BTC",
      "symbol": "WBTC",
      "address": "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
      "chainId": 1,
      "decimals": 8,
      "logoURI": "https://tokens.pancakeswap.finance/images/eth/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599.png"
    },
    {
      "name": "USD Coin",
      "address": "0xaf88d065e77c8cc2239327c5edb3a432268e5831",
      "symbol": "USDC",
      "decimals": 6,
      "chainId": 42161,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "USD Coin",
      "symbol": "USDC",
      "address": "0x176211869cA2b568f2A7D4EE941E073a821EE1ff",
      "chainId": 59144,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "USD Coin",
      "symbol": "USDC",
      "address": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      "chainId": 8453,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/polygon-zkevm/0xA8CE8aee21bC2A48a5EF670afCc9274C7bbbC035.png"
    }
  ]
}

=== 9mm-exchange/9mm-frontend-v4/apps/aptos/config/constants/tokenLists/pancake-default.tokenlist.json
{
  "name": "9mm Swap Default Aptos List",
  "timestamp": "2022-01-26T11:45:09Z",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "tags": {},
  "logoURI": "https://pancakeswap.finance/logo.png",
  "keywords": ["9mm", "default", "aptos"],
  "schema": "aptos",
  "tokens": [
    {
      "name": "BNB",
      "symbol": "BNB",
      "chainId": 34,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetBNB",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/bnb.png"
    },
    {
      "name": "Bitcoin",
      "symbol": "BTC",
      "chainId": 34,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetBTC",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/wbtc.png"
    },
    {
      "name": "Dai",
      "symbol": "DAI",
      "chainId": 34,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetDAI",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/dai.png"
    },
    {
      "name": "Ethereum",
      "symbol": "ETH",
      "chainId": 34,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetETH",
      "logoURI": "https://pancakeswap.finance/images/tokens/0x2170Ed0880ac9A755fd29B2688956BD959F933F8.png"
    },
    {
      "name": "USD coin",
      "symbol": "USDC",
      "chainId": 34,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetUSDC",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "Tether",
      "symbol": "USDT",
      "chainId": 34,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetUSDT",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdt.png"
    },
    {
      "name": "BNB",
      "symbol": "BNB",
      "chainId": 2,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetBNB",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/bnb.png"
    },
    {
      "name": "Bitcoin",
      "symbol": "BTC",
      "chainId": 2,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetBTC",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/wbtc.png"
    },
    {
      "name": "Dai",
      "symbol": "DAI",
      "chainId": 2,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetDAI",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/dai.png"
    },
    {
      "name": "Ethereum",
      "symbol": "ETH",
      "chainId": 2,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetETH",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/weth.png"
    },
    {
      "name": "USD coin",
      "symbol": "USDC",
      "chainId": 2,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetUSDC",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "Tether USD",
      "symbol": "USDT",
      "chainId": 2,
      "decimals": 8,
      "address": "0x8c805723ebc0a7fc5b7d3e7b75d567918e806b3461cb9fa21941a9edc0220bf::devnet_coins::DevnetUSDT",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdt.png"
    },
    {
      "name": "LayerZero - USD coin",
      "symbol": "lzUSDC",
      "chainId": 1,
      "decimals": 6,
      "address": "0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDC",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "LayerZero - Tether USD",
      "symbol": "lzUSDT",
      "chainId": 1,
      "decimals": 6,
      "address": "0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDT",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdt.png"
    },
    {
      "name": "LayerZero - Wrapped Ether",
      "symbol": "lzWETH",
      "chainId": 1,
      "decimals": 6,
      "address": "0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::WETH",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/weth.png"
    },
    {
      "name": "Celer - USD Coin",
      "symbol": "ceUSDC",
      "chainId": 1,
      "decimals": 6,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::UsdcCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "Celer - Tether USD",
      "symbol": "ceUSDT",
      "chainId": 1,
      "decimals": 6,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::UsdtCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdt.png"
    },
    {
      "name": "Celer - Dai Stablecoin",
      "symbol": "ceDAI",
      "chainId": 1,
      "decimals": 8,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::DaiCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/dai.png"
    },
    {
      "name": "Celer - Wrapped Ether",
      "symbol": "ceWETH",
      "chainId": 1,
      "decimals": 8,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::WethCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/weth.png"
    },
    {
      "name": "Celer - Wrapped BTC",
      "symbol": "ceWBTC",
      "chainId": 1,
      "decimals": 8,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::WbtcCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/wbtc.png"
    },
    {
      "name": "Celer - Binance Coin",
      "symbol": "ceBNB",
      "chainId": 1,
      "decimals": 8,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::BnbCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/bnb.png"
    },
    {
      "name": "Celer - Binance USD",
      "symbol": "ceBUSD",
      "chainId": 1,
      "decimals": 8,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::BusdCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/busd.png"
    },
    {
      "name": "Wormhole - Binance USD",
      "symbol": "whBUSD",
      "chainId": 1,
      "decimals": 8,
      "address": "0xccc9620d38c4f3991fa68a03ad98ef3735f18d04717cb75d7a1300dd8a7eed75::coin::T",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/busd.png"
    },
    {
      "name": "Wormhole - Wrapped Ether",
      "symbol": "whWETH",
      "chainId": 1,
      "decimals": 8,
      "address": "0xcc8a89c8dce9693d354449f1f73e60e14e347417854f029db5bc8e7454008abb::coin::T",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/weth.png"
    },
    {
      "name": "Wormhole - USD Coin",
      "symbol": "whUSDC",
      "chainId": 1,
      "decimals": 6,
      "address": "0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea::coin::T",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "9mm Swap Token",
      "symbol": "CAKE",
      "chainId": 1,
      "decimals": 8,
      "address": "0x159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca6::oft::CakeOFT",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0x159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca6::oft::CakeOFT.png"
    }
  ]
}
